name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout FTC Robot Controller
      uses: actions/checkout@v3
      with:
        repository: FIRST-Tech-Challenge/FtcRobotController
    - name: checkout team code
      uses: actions/checkout@v3
      with:
        path: ./TeamCode/src/main/java/org/firstinspires/ftc/teamcode

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
